// 길드원과 즐겨찾기를 최대 열 명까지 비교하고 추월 예상 프리셋을 관리합니다.
import {useEffect,useMemo,useState} from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {ChevronDown,Plus,Save,Trash2,X} from "lucide-react";
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import type {Snapshot} from "./types";
import {Avatar} from "./Avatar";
import {compact,periodGain,progressPoints,todayGain} from "./experience";
import {catchupProjection,sevenDayAverage} from "./projections";

type SortKey="today"|"period"|"average"|"catchup";
type Direction="asc"|"desc";
type Preset={id:string;name:string;periodDays:7|30;ocids:string[];sortKey:SortKey;sortDirection:Direction;updatedAt:number};
const STORAGE="maple-chase-presets-v1";
const readPresets=():Preset[]=>{try{const value=JSON.parse(localStorage.getItem(STORAGE)||"[]");return Array.isArray(value)?value:[];}catch{return [];}};
const writePresets=(value:Preset[])=>{try{localStorage.setItem(STORAGE,JSON.stringify(value));}catch{/* 현재 화면에서는 계속 사용할 수 있습니다. */}};
const color=(ocid:string)=>{let hash=0;for(const char of ocid)hash=(hash*31+char.charCodeAt(0))>>>0;return `hsl(${hash%360} 72% 58%)`;};
const presetName=()=>`따라잡기 ${new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",dateStyle:"short",timeStyle:"short",hour12:false}).format(new Date()).replace(" "," ")}`;

function ChaseTooltip({active,payload,label,rows}:{active?:boolean;payload?:any[];label?:string;rows:Snapshot[]}){
 if(!active||!payload?.length)return null;const source=payload[0]?.payload||{};
 return <div className="chart-tooltip chase-tooltip"><b>{label}</b>{rows.map(row=>{const percent=source[row.ocid],gainLabel=source[`${row.ocid}:gainLabel`];return percent===undefined?null:<span key={row.ocid}><i style={{background:color(row.ocid)}}/>{row.basic.character_name}<strong>{percent}% · {gainLabel}</strong></span>;})}</div>;
}

export default function ChasePanel({rows,guildRows,favoriteRows,primary,signedIn,api}:{rows:Snapshot[];guildRows:Snapshot[];favoriteRows:Snapshot[];primary?:Snapshot;signedIn:boolean;api:(path:string,body?:unknown,method?:string)=>Promise<any>}){
 const [open,setOpen]=useState(false),[periodDays,setPeriodDays]=useState<7|30>(30),[draft,setDraft]=useState<string[]>([]),[selected,setSelected]=useState<string[]>([]);
 const [sortKey,setSortKey]=useState<SortKey>("catchup"),[direction,setDirection]=useState<Direction>("asc"),[presets,setPresets]=useState<Preset[]>(readPresets),[message,setMessage]=useState("");
 useEffect(()=>{if(!signedIn)return;void api("/api/chase-presets",undefined,"GET").then(data=>{const remote=(data.presets||[]) as Preset[];const merged=new Map([...presets,...remote].map(item=>[item.id,item]));const values=[...merged.values()].sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,20);setPresets(values);writePresets(values);}).catch(()=>setMessage("로그인 프리셋을 불러오지 못했습니다."));},[signedIn]);
 const selectedRows=useMemo(()=>selected.map(ocid=>rows.find(row=>row.ocid===ocid)).filter(Boolean) as Snapshot[],[selected,rows]);
 const chart=useMemo(()=>{const dates=new Map<string,Record<string,unknown>>();for(const row of selectedRows)for(const point of progressPoints(row,periodDays,__EXP_TABLE__)){const item=dates.get(point.date)||{date:point.date.slice(5)};item[row.ocid]=point.percent;item[`${row.ocid}:gainLabel`]=point.gained===null?"자료 없음":`+${compact(point.gained)}`;dates.set(point.date,item);}return [...dates.values()];},[selectedRows,periodDays]);
 const metrics=useMemo(()=>selectedRows.map(row=>{const average=sevenDayAverage(row,__EXP_TABLE__),catchup=primary?catchupProjection(primary,row,__EXP_TABLE__):null;return {row,today:todayGain(row,__EXP_TABLE__),period:periodGain(row,periodDays,__EXP_TABLE__).value,average,catchup};}),[selectedRows,primary,periodDays]);
 const sorted=useMemo(()=>[...metrics].sort((left,right)=>{const value=(item:typeof left):bigint|null=>sortKey==="today"?item.today:sortKey==="period"?item.period:sortKey==="average"?item.average:item.catchup?.days===null||item.catchup?.days===undefined?null:BigInt(item.catchup.days);const a=value(left),b=value(right);if(a===null||b===null)return a===b?0:a===null?1:-1;const order=a===b?left.row.basic.character_name.localeCompare(right.row.basic.character_name,"ko"):a<b?-1:1;return direction==="asc"?order:-order;}),[metrics,sortKey,direction]);
 function toggle(ocid:string){setDraft(value=>value.includes(ocid)?value.filter(item=>item!==ocid):value.length<10?[...value,ocid]:value);}
 function toggleGroup(group:Snapshot[]){const ids=[...new Set(group.map(row=>row.ocid))],all=ids.every(id=>draft.includes(id));setDraft(value=>all?value.filter(id=>!ids.includes(id)):[...new Set([...value,...ids])].slice(0,10));}
 function create(){if(!draft.length)return;setSelected(draft);setOpen(false);setMessage("");}
 async function save(){if(!selected.length)return;const value:Preset={id:crypto.randomUUID().replace(/-/g,"_"),name:presetName(),periodDays,ocids:selected,sortKey,sortDirection:direction,updatedAt:Math.floor(Date.now()/1000)},next=[value,...presets].slice(0,20);setPresets(next);writePresets(next);if(signedIn)try{await api(`/api/chase-presets/${value.id}`,value,"PUT");}catch{setMessage("브라우저에는 저장했지만 계정 동기화에 실패했습니다.");}}
 async function remove(value:Preset){const next=presets.filter(item=>item.id!==value.id);setPresets(next);writePresets(next);if(signedIn)void api(`/api/chase-presets/${value.id}`,undefined,"DELETE").catch(()=>setMessage("서버 프리셋 삭제를 다시 시도해 주세요."));}
 function load(value:Preset){setPeriodDays(value.periodDays);setSelected(value.ocids);setSortKey(value.sortKey);setDirection(value.sortDirection);}
 const group=(title:string,items:Snapshot[])=><details open className="chase-group"><summary><button type="button" className="group-check" aria-label={`${title} 전체 선택`} onClick={event=>{event.preventDefault();toggleGroup(items);}}>{items.length>0&&items.every(row=>draft.includes(row.ocid))?"✓":""}</button><b>{title}</b><span>{items.length}명</span><ChevronDown/></summary><div>{items.map(row=><label key={row.ocid} className="chase-option"><input type="checkbox" checked={draft.includes(row.ocid)} onChange={()=>toggle(row.ocid)}/><Avatar character={row}/><span><b>{row.basic.character_name}</b><small>{row.basic.character_class} · Lv.{row.basic.character_level}</small></span></label>)}</div></details>;
 return <section className="chase-page"><div className="section-heading"><div><span className="section-kicker">CHASE REPORT</span><h1>따라잡기</h1><p>현재 성장 위치와 최근 7일 속도로 추월 시점을 비교합니다.</p></div><button className="primary-button" onClick={()=>{setDraft(selected);setOpen(true);}}><Plus/>새로 만들기</button></div>{message&&<div className="state-banner warning">{message}</div>}
  <section className="surface chase-chart"><div className="section-heading"><div><h2>경험치율 비교</h2><span className="section-meta">오늘 포함 {periodDays}일 · 최대 10명</span></div><div className="period-control">{([7,30] as const).map(value=><button key={value} aria-pressed={periodDays===value} onClick={()=>setPeriodDays(value)}>{value}일</button>)}</div></div>{selectedRows.length?<div className="chart-area chase-chart-area"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{top:16,right:18,bottom:14,left:-8}}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="date" tick={{fill:"var(--text-muted)"}} axisLine={false}/><YAxis domain={[0,100]} ticks={[0,25,50,75,100]} unit="%" tick={{fill:"var(--text-muted)"}} axisLine={false}/><Tooltip content={<ChaseTooltip rows={selectedRows}/>}/>{selectedRows.map(row=><Line key={row.ocid} dataKey={row.ocid} name={row.basic.character_name} stroke={color(row.ocid)} strokeWidth={2.5} dot={false} connectNulls={false}/>)}</LineChart></ResponsiveContainer></div>:<div className="empty-state"><b>비교할 캐릭터를 선택해 주세요.</b><span>길드와 즐겨찾기에서 최대 10명까지 선택할 수 있습니다.</span></div>}</section>
  <div className="chase-lower"><section className="surface chase-table"><div className="ranking-tools"><div><h2>비교 목록</h2><span className="section-meta">자료가 없는 값은 정렬 마지막에 표시됩니다.</span></div><div className="chase-sort"><select aria-label="정렬 기준" value={sortKey} onChange={event=>setSortKey(event.target.value as SortKey)}><option value="today">오늘 획득량</option><option value="period">{periodDays}일 획득량</option><option value="average">7일 평균</option><option value="catchup">추월 예상일</option></select><button className="quiet-button" onClick={()=>setDirection(value=>value==="asc"?"desc":"asc")}>{direction==="asc"?"오름차순":"내림차순"}</button></div></div>{sorted.map(item=><article className="chase-row" key={item.row.ocid}><Avatar character={item.row}/><div><b>{item.row.basic.character_name}</b><small>Lv.{item.row.basic.character_level} · {item.row.basic.character_exp_rate}%</small></div><span>오늘 <b>{item.today===null?"자료 없음":compact(item.today)}</b></span><span>{periodDays}일 <b>{item.period===null?"자료 없음":compact(item.period)}</b></span><span>일평균 <b>{item.average===null?"자료 없음":compact(item.average)}</b></span><strong>{item.catchup?.label||"대표 확인 필요"}</strong></article>)}</section><aside className="surface preset-panel"><div className="section-heading"><div><h2>프리셋</h2><span className="section-meta">{signedIn?"계정 동기화":"이 기기에 저장"}</span></div><button className="quiet-button" disabled={!selected.length} onClick={()=>void save()}><Save/>저장</button></div>{presets.map(value=><div className="preset-row" key={value.id}><button onClick={()=>load(value)}><b>{value.name}</b><small>{value.periodDays}일 · {value.ocids.length}명</small></button><button aria-label={`${value.name} 삭제`} onClick={()=>void remove(value)}><Trash2/></button></div>)}{!presets.length&&<p className="muted">저장된 프리셋이 없습니다.</p>}</aside></div>
  <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content chase-dialog"><div className="dialog-titlebar"><div><span className="section-kicker">NEW REPORT</span><Dialog.Title>따라잡을 캐릭터 선택</Dialog.Title><Dialog.Description>최대 10명 · 현재 {draft.length}명 선택</Dialog.Description></div><Dialog.Close className="icon-button"><X/></Dialog.Close></div><div className="period-control chase-period">{([7,30] as const).map(value=><button key={value} aria-pressed={periodDays===value} onClick={()=>setPeriodDays(value)}>{value}일</button>)}</div>{group(primary?.basic.character_guild_name||"길드",guildRows)}{group("즐겨찾기",favoriteRows)}<button className="primary-button chase-create" disabled={!draft.length} onClick={create}>따라잡으러 가기</button></Dialog.Content></Dialog.Portal></Dialog.Root>
 </section>;
}
