// 캐릭터 설정과 로그인 및 계정 관리를 순위 화면과 분리된 대화상자로 제공합니다.
import * as Dialog from "@radix-ui/react-dialog";
import {HelpCircle,LogIn,Save,Trash2,X} from "lucide-react";
import type {DirectStatus} from "./directProtocol";
import {DIRECT_PATH} from "./appMode";

export default function SettingsDialog({open,onOpenChange,primary,setPrimary,signedIn,directOrigin,directStatus,onSave,onLogin,onLogout,onDelete}:{open:boolean;onOpenChange:(value:boolean)=>void;primary:string;setPrimary:(value:string)=>void;signedIn:boolean;directOrigin:string;directStatus:DirectStatus;onSave:()=>void;onLogin:()=>void;onLogout:()=>void;onDelete:()=>void}){
 return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="dialog-overlay"/><Dialog.Content className="dialog-content"><div className="dialog-titlebar"><div><span className="section-kicker">SETTINGS</span><Dialog.Title>내 캐릭터 설정</Dialog.Title><Dialog.Description>로그인하지 않아도 모든 조회 기능을 사용할 수 있습니다.</Dialog.Description></div><Dialog.Close className="icon-button" aria-label="설정 닫기"><X/></Dialog.Close></div>
  <label className="field">대표캐릭터<input value={primary} onChange={event=>setPrimary(event.target.value)} maxLength={20} placeholder="캐릭터 닉네임"/></label>
  <button className="primary-button" onClick={onSave}><Save/>설정 저장</button>
  <section className="direct-settings"><div className="section-heading"><div><b>내 서비스 키로 직접 조회</b><p>{directStatus.message}</p></div><span className={directStatus.keyStored&&directStatus.serviceConfirmed?"direct-state ready":"direct-state"}>{!directStatus.cacheReady?"확인 중":directStatus.keyStored?"키 저장됨":"키 필요"}</span></div><div className="direct-times"><span>마지막 성공 {directStatus.lastSuccessAt?new Date(directStatus.lastSuccessAt).toLocaleString("ko-KR"):"아직 없음"}</span><span>다음 예정 {directStatus.nextRefreshAt?new Date(directStatus.nextRefreshAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",hour12:false}):"설정 후 계산"}</span>{directStatus.metrics&&<span>최근 조회 {directStatus.metrics.latestMs===null?"계산 중":`${(directStatus.metrics.latestMs/1000).toFixed(1)}초`} · 요청 {directStatus.metrics.requests}건{directStatus.metrics.rateLimits?` · 감속 ${directStatus.metrics.rateLimits}회`:""}</span>}</div>{directStatus.busy&&<div className="direct-progress"><span style={{width:`${directStatus.progressPercent}%`}}/></div>}<iframe title="NEXON 서비스 키 설정" src={`${directOrigin}${DIRECT_PATH}/?embed=1`} sandbox="allow-scripts allow-same-origin" allow="clipboard-read"/></section>
  <div className="notice settings-record-note"><HelpCircle/><div><b>기록 안내</b><p>웹은 이 페이지가 열려 있을 때 15분마다 사용자 서비스 키로 직접 조회합니다. 기록과 키는 이 기기에만 저장됩니다.</p><p>자정 또는 오전 2시 근처의 획득량은 NEXON API 날짜 경계상 공식 일별 기록이 준비되면 재정렬될 수 있습니다. 누락 자료는 0으로 처리하지 않습니다.</p></div></div>
  <div className="account-box"><div><b>{signedIn?"기기 간 설정 동기화 중":"PC와 휴대폰 설정 연동"}</b><p>{signedIn?"Google 계정에 연결된 대표캐릭터·즐겨찾기·따라잡기 프리셋을 사용합니다.":"Google로 로그인하면 PC와 휴대폰의 대표캐릭터·즐겨찾기·따라잡기 프리셋이 같아집니다. 서비스 키와 조회 기록은 각 기기에만 저장됩니다."}</p></div>{signedIn?<button className="quiet-button" onClick={onLogout}>로그아웃</button>:<button className="primary-button" onClick={onLogin}><LogIn/>Google로 로그인</button>}</div>
  {signedIn&&<button className="danger-button" onClick={onDelete}><Trash2/>계정 탈퇴</button>}
 </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
